[toolchain]
package_manager = "npm"
anchor_version = "1.0.0-rc.5"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_axelar_gas_service = "gasUBnVr9GZon2cp8X5gyFrUsQFhzrprjy734Ci6Bmn"
solana_axelar_gateway = "gtwT4uGVTYSPnTGv6rSpMheyFyczUicxVWKqdtxNGw9"
solana_axelar_governance = "gov9rPeepKWAL17wJAsy7kdib3ELWjj3kYPBtavkaGc"
solana_axelar_its = "itsYxmqAxNKUL5zaj3fD1K1whuVhqpxKVoiLGie1reF"
solana_axelar_memo = "memKnP9ex71TveNFpsFNVqAYGEe1v9uHVsHNdFPW6FY"
solana_axelar_operators = "oprVNGMBsXzJJBTDQasNWqQ8nZqNhJP2ZXvrC7b5xXd"

[programs.devnet]
solana_axelar_gas_service = "gasUBnVr9GZon2cp8X5gyFrUsQFhzrprjy734Ci6Bmn"
solana_axelar_gateway = "gtwT4uGVTYSPnTGv6rSpMheyFyczUicxVWKqdtxNGw9"
solana_axelar_governance = "gov9rPeepKWAL17wJAsy7kdib3ELWjj3kYPBtavkaGc"
solana_axelar_its = "itsYxmqAxNKUL5zaj3fD1K1whuVhqpxKVoiLGie1reF"
solana_axelar_memo = "memKnP9ex71TveNFpsFNVqAYGEe1v9uHVsHNdFPW6FY"
solana_axelar_operators = "oprVNGMBsXzJJBTDQasNWqQ8nZqNhJP2ZXvrC7b5xXd"

# Solana itself doesn't have stagenet but keeping it here
# for consistency with other networks
[programs.stagenet]
solana_axelar_gas_service = "gasgy6jz24wrfZL98uMy8QFUFziVPZ3bNLGXqnyTstW"
solana_axelar_gateway = "gtwYHfHHipAoj8Hfp3cGr3vhZ8f3UtptGCQLqjBkaSZ"
solana_axelar_governance = "gove5RYbmvEHyqweWehSnVA7GM1RUSXdNjzPDU37bgD"
solana_axelar_its = "itsm3zZhp2oGgEfq7XBu9ojRCYZJnhzecbAEPCrvx2B"
solana_axelar_memo = "mem4E22pPgkbHAvoUYHa7HybBgUKn6jFjvj1YnPdkaq"
solana_axelar_operators = "oprNyqaxdvxs9s3Ngyi1gHqXeM2QLTv8skVPCcqmekx"

[programs.testnet]
solana_axelar_its = "itsJo4kNJ3mdh3requwbtTTt7vyYTudp1pxhn2KiHMc"
solana_axelar_governance = "gov8RocHyma92s2VmF2EXwphqV9wefm9KHJKUaPGRvX"
solana_axelar_memo = "mem7UJouaeyTgySvXhQSxWtGFrWPQ89jywjc8YvQFRT"
solana_axelar_operators = "opriTiaaV7Ew1kma71TjKbrwQ2RWKJ3wbiWEAp3hUZc"
solana_axelar_gas_service = "gasq7KHHv9Rs8C82hu3dgoBD9wk5LTKpWqbdf5o5juu"
solana_axelar_gateway = "gtwJ8LWDRWZpbvCqp8sDeTgy3GSyuoEsiaKC8wSXJqq"

[programs.mainnet]
solana_axelar_its = "itsAUdHnV2K99ppbM6d6WUDac8MD54RAE7dUKHnw1Eg"
solana_axelar_governance = "gov8EenfCgBTzVQR5akuVxnTUuAw5AJN9Ce9c2yJfMg"
solana_axelar_memo = "memtaCuA26EANM26matPAhiQGPnvsrYdJYrYcK8wcon"
solana_axelar_operators = "opre2VP8uvjq3YS15NRhRagsWvsY5DybitvCeLPAwbK"
solana_axelar_gas_service = "gaszjG8797GGm8oACCzH2KLLifGp2nugKkLwaecwBjT"
solana_axelar_gateway = "gtwqvLL93XK7pC2eMvfGamqokvs19AytzaVhrL2iKiz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
