name: "Setup Repo Action"
description: "A reusable composite action that setups rust and other common tasks"
inputs:
  cache-key:
    description: "Cache namespace"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Remove stable toolchain
      shell: bash
      run: rustup toolchain uninstall "stable" || true

    - name: Setup Rust toolchain
      id: rust
      uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1
      with:
        cache: false
        rustflags: ""
        components: clippy, rustfmt

    - name: Cache Rust dependencies
      uses: useblacksmith/rust-cache@f53e7f127245d2a269b3d90879ccf259876842d5 # v3.0.1
      id: cache
      with:
        prefix-key: "${{ steps.rust.outputs.cachekey }}-rust"
        shared-key: "${{ inputs.cache-key }}"
        cache-on-failure: true

    - name: Log crates.toml on cache hit
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "Cache hit for key: ${{ steps.cache.outputs.cache-matched-key }}"
        cat /home/runner/.cargo/.crates.toml || true

    - name: Install Solana
      shell: bash
      run: |
        curl -sSfL https://release.anza.xyz/v2.2.14/install | sh
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Install needed tooling (needed for solana deps)
      shell: bash
      run: |
        sudo apt-get install -y protobuf-compiler bzip2 clang libclang-dev llvm-dev

    - name: Install deps for rust check and docs
      shell: bash
      run: |
        sudo apt-get install -y pkg-config libusb-1.0-0-dev libftdi1-dev
        sudo apt-get install -y libudev-dev
