name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to create release from'
        required: false
        type: string
        default: 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-pr:
    name: Create Release PR
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Check if branch is whitelisted
        id: branch-check
        run: |
          BRANCH_NAME="${{ inputs.ref }}"
          WHITELISTED_BRANCHES=("main" "releases/*")

          IS_WHITELISTED=false
          # Check the branch against the whitelist using wildcard matching
          for BRANCH in "${WHITELISTED_BRANCHES[@]}"; do
            if [[ "$BRANCH_NAME" == $BRANCH ]]; then
              IS_WHITELISTED=true;
              break;
            fi
          done

          if [ "$IS_WHITELISTED" == true ]; then
            echo "Branch is whitelisted: $BRANCH_NAME"
          else
            echo "Branch $BRANCH_NAME is not whitelisted."
            exit 1
          fi

          echo "branch_name=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.branch-check.outputs.branch_name }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@fff938ea2923fdfa35797fff63537b00f30fe6f9 # v0.5.82
        with:
          command: release-pr
          version: "0.3.105"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
