name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to create release from'
        required: false
        type: string
        default: 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  pull-requests: write
  contents: write

jobs:
  release-pr:
    name: Create Release PR
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Check if branch is whitelisted
        id: branch-check
        run: |
          BRANCH_NAME="${{ inputs.ref }}"
          WHITELISTED_BRANCHES=("main" "releases/*")

          IS_WHITELISTED=false
          # Check the branch against the whitelist using wildcard matching
          for BRANCH in "${WHITELISTED_BRANCHES[@]}"; do
            if [[ "$BRANCH_NAME" == $BRANCH ]]; then
              IS_WHITELISTED=true;
              break;
            fi
          done

          if [ "$IS_WHITELISTED" == true ]; then
            echo "Branch is whitelisted: $BRANCH_NAME"
          else
            echo "Branch $BRANCH_NAME is not whitelisted."
            exit 1
          fi

          echo "branch_name=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-check.outputs.branch_name }}
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
